In [22]:
import numpy as np
from utils.model_utils import lasso_cd
from utils.test_utils import l2_scale, generate_data

In [23]:
X, y, beta_true, bias_true = generate_data(n = 20, p = 5)
X_l2 = l2_scale(X)
beta_true, bias_true

(array([21, 22, 63, 43, 63], dtype=int32), 10)

In [24]:
beta_true

array([21, 22, 63, 43, 63], dtype=int32)

In [25]:
lasso_cd(X, y, 0.001, tol = 1e-10)

array([21.0386302 , 21.95392152, 62.93928401, 42.91692353, 63.06871097])

In [26]:
from sklearn.linear_model import Lasso

model = Lasso(alpha = 0.001, fit_intercept = False).fit(X, y)

In [27]:
model.coef_

array([21.31226658, 22.31991288, 63.55614569, 43.39185678, 63.53246499])